# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistdc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='preview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
